/**
 * IDX XML生成器
 * 
 * @description
 * 基于xmlbuilder2的IDX专用XML生成器，提供便捷的API和优秀的注释支持。
 */

import { create } from 'xmlbuilder2';
import { IDXDocument } from '../types/idx-structure';

/**
 * XML格式化选项
 */
export interface XMLFormatOptions {
  /** 是否美化输出 */
  prettyPrint?: boolean;
  /** 缩进字符串 */
  indent?: string;
  /** 换行符 */
  newline?: string;
}

/**
 * IDX XML生成器类
 * 
 * @description
 * 提供流式API用于生成IDX V4.5格式的XML文档，支持注释和格式化。
 */
export class IDXXMLGenerator {
  private doc: any;
  private formatOptions: XMLFormatOptions;

  /**
   * 创建IDX XML生成器实例
   * 
   * @param options - XML格式化选项
   */
  constructor(options?: XMLFormatOptions) {
    this.formatOptions = {
      prettyPrint: true,
      indent: '  ',
      newline: '\n',
      ...options
    };
    
    this.doc = create({ version: '1.0', encoding: 'UTF-8' });
  }

  /**
   * 添加注释
   * 
   * @param comment - 注释内容（字符串或字符串数组）
   * @returns 当前实例，支持链式调用
   */
  addComment(comment: string | string[]): this {
    this.doc = this.doc.com(comment);
    return this;
  }

  /**
   * 开始IDX文档根元素
   * 
   * @returns 当前实例，支持链式调用
   */
  startDocument(): this {
    this.doc = this.doc.ele('foundation:EDMDDataSet', {
      'xmlns:foundation': 'http://www.prostep.org/ecad-mcad/edmd/4.0/foundation',
      'xmlns:pdm': 'http://www.prostep.org/ecad-mcad/edmd/4.0/pdm',
      'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance'
    });
    return this;
  }

  /**
   * 生成完整的IDX XML文档
   * 
   * @param document - IDX文档对象
   * @returns XML字符串
   */
  generateIDXDocument(document: IDXDocument): string {
    this.addComment('IDX V4.5 Document - Generated by IDXPorter');
    this.startDocument();
    
    // 添加Header
    this.addComment('Document Header');
    this.addHeader(document.header);
    
    // 添加Body
    this.addComment('Document Body - Contains all design elements');
    this.addBody(document.body);
    
    // 添加ProcessInstruction
    this.addComment('Process Instruction');
    this.addProcessInstruction(document.processInstruction);
    
    return this.toString();
  }

  /**
   * 添加Header元素
   */
  private addHeader(header: any): void {
    const headerEle = this.doc.ele('foundation:Header');
    
    if (header.creatorCompany) {
      headerEle.ele('foundation:CreatorCompany').txt(header.creatorCompany).up();
    }
    if (header.creatorSystem) {
      headerEle.ele('foundation:CreatorSystem').txt(header.creatorSystem).up();
    }
    if (header.creator) {
      headerEle.ele('foundation:Creator').txt(header.creator).up();
    }
    if (header.creationDateTime) {
      headerEle.ele('foundation:CreationDateTime').txt(header.creationDateTime).up();
    }
    
    headerEle.ele('foundation:GlobalUnitLength').txt(header.globalUnitLength).up();
    
    headerEle.up();
  }

  /**
   * 添加Body元素
   */
  private addBody(body: any): void {
    const bodyEle = this.doc.ele('foundation:Body');
    
    // 添加Items
    if (body.items && body.items.length > 0) {
      this.doc.com(`Items (${body.items.length} total)`);
      for (const item of body.items) {
        this.addItem(item);
      }
    }
    
    bodyEle.up();
  }

  /**
   * 添加Item元素
   */
  private addItem(item: any): void {
    const attrs: any = {
      id: item.id,
      itemType: item.itemType
    };
    
    if (item.geometryType) {
      attrs.geometryType = item.geometryType;
    }
    
    const itemEle = this.doc.ele('foundation:Item', attrs);
    
    itemEle.ele('foundation:Name').txt(item.name).up();
    
    if (item.description) {
      itemEle.ele('foundation:Description').txt(item.description).up();
    }
    
    itemEle.up();
  }

  /**
   * 添加ProcessInstruction元素
   */
  private addProcessInstruction(pi: any): void {
    this.doc.ele('foundation:ProcessInstruction')
      .ele('foundation:' + pi.type)
      .up()
      .up();
  }

  /**
   * 转换为XML字符串
   * 
   * @returns 格式化的XML字符串
   */
  toString(): string {
    return this.doc.end({
      prettyPrint: this.formatOptions.prettyPrint,
      indent: this.formatOptions.indent,
      newline: this.formatOptions.newline
    });
  }

  /**
   * 重置生成器状态
   */
  reset(): void {
    this.doc = create({ version: '1.0', encoding: 'UTF-8' });
  }
}